spring.application.name=school-management-system


# MySQL Database Configuration
# ===============================


server.port=8080


spring.datasource.url=jdbc:mysql://mysql-263f936-edusphere6517.l.aivencloud.com:24951/defaultdb?ssl-mode=REQUIRED

spring.datasource.username=avnadmin

spring.datasource.password=AVNS_gM3HmsYdyP8apTAdNNt


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# ===============================
# Thymeleaf Configuration
# ===============================
spring.thymeleaf.cache=false




#=============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ramkumar651763@gmail.com
spring.mail.password=vslzezenqaeykinm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.debug=true
